/**
 * IAIService Port
 * Interface for AI-related operations like chat generation and embeddings.
 */

/** Request payload for AI chat interactions */
export interface AIChatRequest {
  /** The user's question or query */
  query: string;
  /** Previous messages in the conversation for context */
  history: Array<{ role: 'user' | 'model'; content: string }>;
  /** Optional list of document snippets to use as context (RAG) */
  contextDocuments?: string[];
}

/** Response payload from AI chat interactions */
export interface AIChatResponse {
  /** The text response generated by the AI */
  text: string;
  /** Optional references to source documents used in the response */
  sourceReferences?: string[];
}

export interface IAIService {
  /** Generates a conversational response based on query and history */
  generateResponse(request: AIChatRequest): Promise<AIChatResponse>;
  /** Generates a numerical embedding vector for a given text snippet */
  embedText(text: string): Promise<number[]>;
}
